spring.application.name=transaction-management-system

spring.datasource.url=jdbc:mysql://localhost:3306/transaction_management
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.servlet.session.timeout=30m